
const Constants = {
    web3storagetoken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGE4MjU5MDcyYkUxRmEwODhhZTA3MTI3OTg2NDVEY0VBRjFGNDMzREQiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTgyMjcyNTE1MTgsIm5hbWUiOiJvbm4ifQ.6AAz_KHuowFfJcxlf0jHbRoVEAKMv6iER_WSYkaUtr0',
}

export default Constants;