
const Constants = {
    web3storagetoken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGE4MjU5MDcyYkUxRmEwODhhZTA3MTI3OTg2NDVEY0VBRjFGNDMzREQiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjExNjkyNDI2NTEsIm5hbWUiOiJvbnVuIn0.2Jvk1I7DmMf6oHGIccBXQ5tuzYcEMZjvlEry7SVB5n8',
}

export default Constants;